"""add followers

Revision ID: 347902d75533
Revises: 96124a494124
Create Date: 2022-07-01 15:47:06.008087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347902d75533'
down_revision = '96124a494124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
