"""add about me, create time for user

Revision ID: 96124a494124
Revises: d5cdc4252f2b
Create Date: 2022-07-01 02:36:59.499550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96124a494124'
down_revision = 'd5cdc4252f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
